#pragma once
#include <d3dx9.h>

struct CUSTOMVERTEX {
	D3DXVECTOR3 pos;
	D3DXVECTOR3 nor;
	DWORD color;
	D3DXVECTOR2 tex;
};

#define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZ|D3DFVF_NORMAL|D3DFVF_DIFFUSE|D3DFVF_TEX1)
